# Project: »˝◊”∆Â
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ≤‚ ‘.o ”Œœ∑.o
LINKOBJ  = ≤‚ ‘.o ”Œœ∑.o
LIBS     = -L"E:/DEV-C++/Dev-Cpp/MinGW64/lib" -L"E:/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/DEV-C++/Dev-Cpp/MinGW64/include" -I"E:/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/DEV-C++/Dev-Cpp/MinGW64/include" -I"E:/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = »˝◊”∆Â.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

≤‚ ‘.o: ≤‚ ‘.c
	$(CC) -c ≤‚ ‘.c -o ≤‚ ‘.o $(CFLAGS)

”Œœ∑.o: ”Œœ∑.c
	$(CC) -c ”Œœ∑.c -o ”Œœ∑.o $(CFLAGS)
