#include <stdio.h>

int main()
{
	int n,k,max,min,n0[100020],i,j,m;
	scanf("%d%d",&n,&k);
	for(i=1;i<=n;i++)
	scanf("%d",&n0[i]);
	if(n<k)
	{
		min=100;
		for(i=1;i<=n;i++)
		{
			if(min>n0[i])
			min=n0[i];
		}
		printf("%d",min);
	}
	else
	{
		do
		{
			if(n%k==0)
			{
				n=n/k;
				for(i=0;i<n;i++)
				{
					for(max=0,j=1;j<=k;j++)
					{
						if(n0[i*k+j]>max)
								max=n0[i*k+j];
					}
					for(min=100,j=1;j<=k;j++)
					{
						if(n0[i*k+j]<min)
						min=n0[i*k+j];
					}
					n0[i+1]=max;
					printf("%d\n",min);
				}			
			}
			else
			{
				m=n%k;
				n=n/k;
				for(i=0;i<n-1;i++)
				{
					for(max=0,j=1;j<=k;j++)
					{
						if(n0[i*k+j]>max)
								max=n0[i*k+j];
					}
					for(min=100,j=1;j<=k;j++)
					{
						if(n0[i*k+j]<min)
						min=n0[i*k+j];
					}
					n0[i+1]=max;
					printf("%d\n",min);
				}
				for(max=0,j=1;j<=k+m;j++)
				{
					if(n0[i*k+j]>max)
					max=n0[i*k+j];
				}
				for(min=100,j=1;j<=k+m;j++)
				{
					if(n0[i*k+j]<min)
					min=n0[i*k+j];
				}
				n0[i+1]=max;
				printf("%d\n",min);
			}
		}
		while(n>=k);
		for(min=100,i=1;i<=n;i++)
		{
			if(n0[i]<min)
			min=n0[i];
		}
		printf("%d\n",min);
	}
 	return 0;
}

